### ISSUE TITLE
enquiry about the annotation file preparation for eoulsan

### ISSUE THREAD

**Issue by zhuxqdoctor** [GenomicParisCentre/eoulsan#5]
Hi, I am new to bioinformatics. I have 10X genomic scRNA data and want to use eoulsan to analyze. I have read the tutorials of eoulsan and not sure about the annotation file preparation for eoulsan. I want to use hg19 version for annotation. So far, I have hg19.gtf file and I am wondering if the .gff and .tsv file is also compulsory. I have find a approach to convert .gtf to gff file. However, I don't know where I can get the .tsv file for annotation. Can you guys give me any suggestion. Many thanks.

**Comment by jourdren** [comment]
Dear zhuxqdoctor,

The GFF file is currently mandatory, however this limitation will soon be removed as we will update our 10X workflow to use the standard expression module as for the bulk RNA-Seq workflow.

The TSV file is also mandatory but you can use an empty TSV file. The "rsinglecellexperimentcreator" is currently under development and in the next version of Eoulsan, the usage of this TSV file will be optional.

Best regards,

Laurent.
