### ISSUE TITLE
errors when running eoulsan using sample dataset

### ISSUE THREAD

**Issue by zhuxqdoctor** [GenomicParisCentre/eoulsan#6]
Hi, I have tried to used sample dataset according to the eoulsan tutorial. However, I got an error like this: 
=== Eoulsan Error ===
java.io.IOException: com.spotify.docker.client.DockerException: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.io.IOException: No such file or directory. I suspect this java.io.IOException is not in eoulsan package. Can anyone tell me how to fix it. Thanks.

**Comment by zhuxqdoctor** [comment]
In additional, my steps displayed that the docker installation was failed. I run in linux operating system. Does that mean I need to install docker before run eouslan?
Eoulsan version 2.3 (v2.3-0-g09a038b, build0 build on 097c158f6152, 2018-09-13 11:11:17 UTC)
 * Step checker                                  DONE
 * Step genomedescgenerator                      DONE
 * Step step5createstarindex                     DONE
 * Step dockerinstall1                           FAILED
 * Workflow                                      FAILED  (Job done in 01:27:36.396 s.)

=== Eoulsan Error ===
java.io.IOException: com.spotify.docker.client.DockerException: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.io.IOException: No such file or directory

**Comment by zhuxqdoctor** [comment]
Fortunately, I have figured out this issue focusing on docker. However, after I fixed it and run again, another error came out in the latter steps just like this: 
=== Eoulsan Error ===
/home/zhuxq/nas/Xiaoqiang/SYL_scRNA/test.Eoulsan/eoulsan-20181025-100329/tmp/17fe6a4b-a568-41ff-8e2c-ab5891752423/hgmmR1.samlog.
Do you guys have any suggestions? Thanks in advance.

**Comment by jourdren** [comment]
Dear zhuxqdoctor,

This is strange error. Could you relaunch your workflow with the following global section parameter to enabled fine logging and then send me the stack trace.

    <globals>
        <parameter>
                <name>main.printstacktrace</name>
                <value>true</value>
        </parameter>
    </globals>

Best regards,

Laurent.

**Comment by zhuxqdoctor** [comment]
Hi jourdren,
I have tried to run again after I modified the xml file just like you suggested. But I got errors at the step5(creating the STARindex). The details are as below. Do you have any suggestions about this. Thanks.
zhuxq@ctcf:~/nas/Xiaoqiang/SYL_scRNA/FASTQ/CB8E5ANXX/SYL1.eoulsan$ eoulsan.sh exec workflow-scrnaseq-chromium.xml design.txt
Eoulsan version 2.3 (v2.3-0-g09a038b, build0 build on 097c158f6152, 2018-09-13 11:11:17 UTC)
 * Step checker                                  DONE
 * Step genomedescgenerator                      DONE
 * Step step5createstarindex                       0%    (0/1 task done, 1 task running)
19% workflow done
19% workflow done
19% workflow done
31% workflow done
31% workflow done
44% workflow done
56% workflow done
63% workflow done
69% workflow done
75% workflow done
75% workflow done
 * Workflow                                      FAILED  (Job done in 03:06:46.047 s.)

=== Eoulsan Error ===
/home/zhuxq/nas/Xiaoqiang/SYL_scRNA/FASTQ/CB8E5ANXX/SYL1.eoulsan/eoulsan-20181101-173224/tmp/d45fbddd-7599-421c-86a3-04b6f515                                                                                                                3641/SYL1.samlog

=== Eoulsan Debug Stack Trace ===
java.nio.file.AccessDeniedException: /home/zhuxq/nas/Xiaoqiang/SYL_scRNA/FASTQ/CB8E5ANXX/SYL1.eoulsan/eoulsan-20181101-173224                                                                                                                /tmp/d45fbddd-7599-421c-86a3-04b6f5153641/SYL1.samlog
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.createSymbolicLink(UnixFileSystemProvider.java:457)
        at java.nio.file.Files.createSymbolicLink(Files.java:1043)
        at fr.ens.biologie.genomique.eoulsan.data.protocols.FileDataProtocol.symlink(FileDataProtocol.java:227)
        at fr.ens.biologie.genomique.eoulsan.data.DataFile.symlink(DataFile.java:484)
        at fr.ens.biologie.genomique.eoulsan.data.DataFile.symlink(DataFile.java:452)
        at fr.ens.biologie.genomique.eoulsan.modules.multiqc.MapperInputPreprocessor.preprocess(MapperInputPreprocessor.java:                                                                                                                57)
        at fr.ens.biologie.genomique.eoulsan.modules.multiqc.MultiQCModule.execute(MultiQCModule.java:167)
        at fr.ens.biologie.genomique.eoulsan.core.workflow.TaskRunner$1.run(TaskRunner.java:196)
        at java.lang.Thread.run(Thread.java:745)

**Comment by jourdren** [comment]
Hi zhuxqdoctor,
It seems to be a right issue between your NAS and Docker. The following command may not work on your system:
```bash
$ docker run --rm -it -u $(id -u):$(id -g)  -v  /home/zhuxq/nas/Xiaoqiang/SYL_scRNA/FASTQ/CB8E5ANXX/SYL1.eoulsan:/home/zhuxq/nas/Xiaoqiang/SYL_scRNA/FASTQ/CB8E5ANXX/SYL1.eoulsan -w /home/zhuxq/nas/Xiaoqiang/SYL_scRNAFASTQ/CB8E5ANXX/SYL1.eoulsan ubuntu:18.04
```
You can try to set the "main.docker.mount.nfs.roots" parameter to true in your global section of your workflow file. If this option is enabled, when mounted data in a Docker container are stored in a NFS volume, mount the root the of NFS volume instead of data path. This option avoid some right issues with NFS root squash.

Best regards,

Laurent.
