### ISSUE TITLE
line 97: java: command not found

### ISSUE THREAD

**Issue by webyoung** [GenomicParisCentre/eoulsan#8]
when I ran eoulsan.sh I just got this:
./eoulsan.sh: line 97: java: command not found

What should I do?

**Comment by xbauquet** [comment]
Hi, 
- Make sure you're in the right folder (The one with the file eoulsan.sh)
- Make sure eoulsan.sh is executable by using the command: `chmod +x eoulsan.sh`
This should fix your problem.

**Comment by webyoung** [comment]
Yes, I am sure I am running in the right folder and also did the chmod step. If I did not do as this I can not get error like above.

**Comment by webyoung** [comment]
I figured out the reason is the java did not run.

**Comment by xbauquet** [comment]
I'm glade you've found an answer to your problem.
Please mark this issue as closed as it has been solved.

**Comment by webyoung** [comment]
OK.  I am going to do it. 

Sent from Yahoo Mail on Android 
 
  On Tue, May 14, 2019 at 12:18 AM, Xavier Bauquet<notifications@github.com> wrote:   
I'm glade you've found an answer to your problem.
Please mark this issue as closed as it has been solved.
